### ISSUE TITLE
build failed - No such file or directory: 'README'

### ISSUE THREAD

**Issue by Joungkyun** [Joungkyun/python-chardet#1]
## What is your problem?

Error when building using setup.py

## OS and Architecture

Enter the ___OS and architecture___ information using the following command: ___CentOS 7___

```bash
[user@host ~]$ python -c 'import platform; print(platform.uname())'
```

## Python version

Enter the your ___version of PYTHON___ using the following command: ___2.7.5___

```bash
[user@host ~]$ python --version
```

## python-chardet version

Enter the your ___version of PYTHON___ using the following command:  60f2c39

```bash
[user@host ~]$ python -c 'import chardet; print(chardet.__version__)'
```

## Expected behavior

no error

## Actual behavior

```bash
[user@host python-chardet-master]$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    long_description=readme(),
  File "setup.py", line 12, in readme
    with open('README') as f:
IOError: [Errno 2] No such file or directory: 'README'
```

## Steps to reproduce the behavior

```bash
[user@host ~]$ cd
[user@host ~]$ git clone https://github.com/Joungkyun/python-chardet.git
Cloning into 'python-chardet'...
remote: Counting objects: 185, done.
remote: Total 185 (delta 0), reused 0 (delta 0), pack-reused 185
Receiving objects: 100% (185/185), 36.91 KiB | 0 bytes/s, done.
Resolving deltas: 100% (117/117), done.
[user@host python-chardet]$ cd python-chardet/
[user@host python-chardet]$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    long_description=readme(),
  File "setup.py", line 12, in readme
    with open('README') as f:
IOError: [Errno 2] No such file or directory: 'README'
[root@an3 python-chardet]#
```

**Comment by Joungkyun** [comment]
This bug is caused by 7249568. There is no problem with the release version.
